
import com.sun.tools.classfile.Opcode;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sun.swing.SwingAccessor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas-pc
 */
public class TelaGastoViagem extends javax.swing.JFrame {

    /**
     * Creates new form TelaGastoViagem
     */
    public TelaGastoViagem() {
        initComponents();
        
        disableAlerError();
        
        pedagio.setText("0");
        
    }

    private void disableAlerError()
    {
        alert1.setVisible(false);
        alert2.setVisible(false);
        alert3.setVisible(false);
        alert4.setVisible(false);   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        distance = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        consume = new javax.swing.JTextField();
        pedagio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        buttonClick = new javax.swing.JLabel();
        alert2 = new javax.swing.JLabel();
        alert3 = new javax.swing.JLabel();
        alert1 = new javax.swing.JLabel();
        alert4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setText("Distancia até o destino");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));
        getContentPane().add(distance, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 210, 20));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 210, 20));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel8.setText("Consumo Por Km");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setText("Preço do Combustivel");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));
        getContentPane().add(consume, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 210, 20));
        getContentPane().add(pedagio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 210, 20));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel9.setText("Custo com pedágios");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        buttonClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsViagem/button black.png"))); // NOI18N
        buttonClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonClickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonClickMouseExited(evt);
            }
        });
        getContentPane().add(buttonClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        alert2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        alert2.setForeground(new java.awt.Color(255, 51, 51));
        alert2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsViagem/alerta.png"))); // NOI18N
        alert2.setText("Campo necessário");
        getContentPane().add(alert2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        alert3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        alert3.setForeground(new java.awt.Color(255, 51, 51));
        alert3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsViagem/alerta.png"))); // NOI18N
        alert3.setText("Campo necessário");
        getContentPane().add(alert3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        alert1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        alert1.setForeground(new java.awt.Color(255, 51, 51));
        alert1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsViagem/alerta.png"))); // NOI18N
        alert1.setText("Campo necessário");
        getContentPane().add(alert1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        alert4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        alert4.setForeground(new java.awt.Color(255, 51, 51));
        alert4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsViagem/alerta.png"))); // NOI18N
        alert4.setText("Campo necessário");
        getContentPane().add(alert4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsViagem/background.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        TelaPrincipal tp = new TelaPrincipal();
        tp.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void buttonClickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClickMouseEntered
     buttonClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsViagem/button blue.png"))); 
    }//GEN-LAST:event_buttonClickMouseEntered

    private void buttonClickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClickMouseExited
        buttonClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsViagem/button black.png"))); 
    }//GEN-LAST:event_buttonClickMouseExited

    private void buttonClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClickMouseClicked
        sum();
    }//GEN-LAST:event_buttonClickMouseClicked

    
    private boolean validateField()
    {  
        boolean check = false;
        
        if(distance.getText().isEmpty())
        {
            check = true;
            alert1.setVisible(true);
        }
        
        if(price.getText().isEmpty())
        {
            check = true;
            alert2.setVisible(true);
        }
        
        if(consume.getText().isEmpty())
        {
            check = true;
            alert3.setVisible(true);
        }
        if(pedagio.getText().isEmpty())
        {
            check = true;
            alert4.setVisible(true);
        }
        
        return check;
    }
    
    private void sum()
    {   
        disableAlerError();
        validateField();
        
        if(!validateField())
        {
            try{
                
                float distance = Float.parseFloat(this.distance.getText().replace(",",".").trim());
                float price = Float.parseFloat(this.price.getText().replace(",",".").trim());
                float consume = Float.parseFloat(this.consume.getText().replace(",",".").trim());
                float pedagio = Float.parseFloat(this.pedagio.getText().replace(",",".").trim());
                
                float sum = ((distance/consume)*price)+pedagio;
                
                ImageIcon icon = new ImageIcon(getClass().getResource("/iconsViagem/dinheiro.png"));
                
                JOptionPane.showMessageDialog(this,"R$ "+sum,"O custo da sua viagem será..",JOptionPane.PLAIN_MESSAGE,icon);
               
                
            }catch(NumberFormatException e){
                 JOptionPane.showMessageDialog(this,"Digite somente valores numericos","Error",JOptionPane.ERROR_MESSAGE,new javax.swing.ImageIcon(getClass().getResource("/iconsViagem/button black.png")));
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGastoViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaGastoViagem().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert1;
    private javax.swing.JLabel alert2;
    private javax.swing.JLabel alert3;
    private javax.swing.JLabel alert4;
    private javax.swing.JLabel buttonClick;
    private javax.swing.JTextField consume;
    private javax.swing.JTextField distance;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pedagio;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
